version: 2
jobs:
  test-node-9:
    working_directory: ~/docs
    docker:
      - image: circleci/node:9
    steps: &teststeps
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: yarn build
      
  test-node-stable:
    working_directory: ~/docs
    docker:
      - image: circleci/node:latest
    steps: *teststeps

workflows:
  version: 2
  test:
    jobs:
      - test-node-9
      - test-node-stable
